### ISSUE TITLE
teas section

### ISSUE THREAD

**Issue by rimmesbe** [cesthree/teacozy#1]
With flex display you should not need separate rows for the images. Just use the typical wrap flex display with justify content center. Then use padding and margin to create space between the teas. Doing it this way will make your section more flexible incase new/more teas need to be added to the section. You won't have to worry about creating new section divs.

https://github.com/cesthree/teacozy/blob/master/index.html#L39-L62

**Comment by cesthree** [comment]
Thank you for the review comment!
