### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [cesthree/teacozy#5]
Grade: Exceeds expectations

Summary: Really nice job on this project, the site look good. Your code is well organized and you used some good techniques. Take a look at the issues I created as they will point out some tweaks you can make to improve things and I would definitely recommend looking into those semantic tags as that is pretty much the accepted practice in modern html development.

**Comment by cesthree** [comment]
I really appreciate your review comments. I will definitely circle-back and address all of these issues, but I have gotten a bit behind in the lessons and need to get on-track!

Thank you!
